# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddtag():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.maximize_window()  # For maximizing window
    self.driver.implicitly_wait(20)  # gives an implicit wait for 20 seconds
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addtag(self):
    self.driver.get("https://freeda.myls.education/#grid-1863_tab")
    self.driver.set_window_size(1124, 894)
    self.driver.find_element(By.NAME, "username").click()  # login
    self.driver.find_element(By.NAME, "username").send_keys("admin@freedaspace.com")  # login
    self.driver.find_element(By.NAME, "password").click()  # login
    self.driver.find_element(By.NAME, "password").send_keys("freedaadmin40")  # login
    self.driver.find_element(By.XPATH, "//div[@id='mylsAuthForm']/div/div/div/div[3]/div/div/div/div/span").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'grid-1863_tab\']/div/div[4]/div/div/div/div/div/div/div/img").click()
    self.driver.find_element(By.NAME, "tag").click()
    self.driver.find_element(By.NAME, "tag").send_keys("test2")
    self.driver.find_element(By.XPATH, "//div[@id=\'form-2094--1_popup_save-button\']/div/span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dx-row-focused > td:nth-child(2)").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'grid-1863_tab\']/div/div[4]/div/div/div/div[3]/div/div/div/img").click()
    self.driver.find_element(By.XPATH, "//div[3]/div/div[2]/div/div/div/div").click()
  
